/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as UatRouteImport } from './routes/uat'
import { Route as AdministrationApprovalPoliciesRouteImport } from './routes/administration.approval-policies'
import { Route as AdministrationContactGroupsRouteImport } from './routes/administration.contact-groups'
import { Route as AdministrationEngagementsRouteImport } from './routes/administration.engagements'
import { Route as AdministrationMonthsRouteImport } from './routes/administration.months'
import { Route as AttendanceLeaveRouteImport } from './routes/attendance.leave'
import { Route as AttendanceMonthCloseRouteImport } from './routes/attendance.month-close'
import { Route as AttendanceRegularizationsRouteImport } from './routes/attendance.regularizations'
import { Route as AttendanceTodayRouteImport } from './routes/attendance.today'
import { Route as CertificationIndexRouteImport } from './routes/certification.index'
import { Route as CertificationMonthIdRouteImport } from './routes/certification.$monthId'
import { Route as ConfirmationIndexRouteImport } from './routes/confirmation.index'
import { Route as ConfirmationMonthIdRouteImport } from './routes/confirmation.$monthId'
import { Route as DeliveryIntegrationHealthRouteImport } from './routes/delivery.integration-health'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceProcurementRouteImport } from './routes/finance.procurement'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as MigrationIndexRouteImport } from './routes/migration.index'
import { Route as WorkforceAdministrationRouteImport } from './routes/workforce.administration'
import { Route as AdministrationApprovalRequestsIndexRouteImport } from './routes/administration.approval-requests.index'
import { Route as AdministrationApprovalRequestsRequestIdRouteImport } from './routes/administration.approval-requests.$requestId'
import { Route as CertificationMonthIdIndexRouteImport } from './routes/certification.$monthId.index'
import { Route as CertificationMonthIdReviewRouteImport } from './routes/certification.$monthId.review'
import { Route as ConfirmationRequestsRequestIdRouteImport } from './routes/confirmation.requests.$requestId'
import { Route as DeliveryPlansIndexRouteImport } from './routes/delivery.plans.index'
import { Route as DeliveryPlansPlanIdRouteImport } from './routes/delivery.plans.$planId'
import { Route as DeliveryPlansNewRouteImport } from './routes/delivery.plans.new'
import { Route as WorkforceEmployeesIndexRouteImport } from './routes/workforce.employees.index'
import { Route as WorkforceEmployeesEmployeeIdRouteImport } from './routes/workforce.employees.$employeeId'
import { Route as DeliveryPlansPlanIdEditRouteImport } from './routes/delivery.plans.$planId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const UatRoute = UatRouteImport.update({
  id: '/uat',
  path: '/uat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationApprovalPoliciesRoute =
  AdministrationApprovalPoliciesRouteImport.update({
    id: '/administration/approval-policies',
    path: '/administration/approval-policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationContactGroupsRoute =
  AdministrationContactGroupsRouteImport.update({
    id: '/administration/contact-groups',
    path: '/administration/contact-groups',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationEngagementsRoute =
  AdministrationEngagementsRouteImport.update({
    id: '/administration/engagements',
    path: '/administration/engagements',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationMonthsRoute = AdministrationMonthsRouteImport.update({
  id: '/administration/months',
  path: '/administration/months',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceLeaveRoute = AttendanceLeaveRouteImport.update({
  id: '/attendance/leave',
  path: '/attendance/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceMonthCloseRoute = AttendanceMonthCloseRouteImport.update({
  id: '/attendance/month-close',
  path: '/attendance/month-close',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRegularizationsRoute =
  AttendanceRegularizationsRouteImport.update({
    id: '/attendance/regularizations',
    path: '/attendance/regularizations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AttendanceTodayRoute = AttendanceTodayRouteImport.update({
  id: '/attendance/today',
  path: '/attendance/today',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationIndexRoute = CertificationIndexRouteImport.update({
  id: '/certification/',
  path: '/certification/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationMonthIdRoute = CertificationMonthIdRouteImport.update({
  id: '/certification/$monthId',
  path: '/certification/$monthId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationIndexRoute = ConfirmationIndexRouteImport.update({
  id: '/confirmation/',
  path: '/confirmation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationMonthIdRoute = ConfirmationMonthIdRouteImport.update({
  id: '/confirmation/$monthId',
  path: '/confirmation/$monthId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIntegrationHealthRoute =
  DeliveryIntegrationHealthRouteImport.update({
    id: '/delivery/integration-health',
    path: '/delivery/integration-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceProcurementRoute = FinanceProcurementRouteImport.update({
  id: '/finance/procurement',
  path: '/finance/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationIndexRoute = MigrationIndexRouteImport.update({
  id: '/migration/',
  path: '/migration/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceAdministrationRoute = WorkforceAdministrationRouteImport.update({
  id: '/workforce/administration',
  path: '/workforce/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationApprovalRequestsIndexRoute =
  AdministrationApprovalRequestsIndexRouteImport.update({
    id: '/administration/approval-requests/',
    path: '/administration/approval-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationApprovalRequestsRequestIdRoute =
  AdministrationApprovalRequestsRequestIdRouteImport.update({
    id: '/administration/approval-requests/$requestId',
    path: '/administration/approval-requests/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CertificationMonthIdIndexRoute =
  CertificationMonthIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CertificationMonthIdRoute,
  } as any)
const CertificationMonthIdReviewRoute =
  CertificationMonthIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => CertificationMonthIdRoute,
  } as any)
const ConfirmationRequestsRequestIdRoute =
  ConfirmationRequestsRequestIdRouteImport.update({
    id: '/confirmation/requests/$requestId',
    path: '/confirmation/requests/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryPlansIndexRoute = DeliveryPlansIndexRouteImport.update({
  id: '/delivery/plans/',
  path: '/delivery/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryPlansPlanIdRoute = DeliveryPlansPlanIdRouteImport.update({
  id: '/delivery/plans/$planId',
  path: '/delivery/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryPlansNewRoute = DeliveryPlansNewRouteImport.update({
  id: '/delivery/plans/new',
  path: '/delivery/plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceEmployeesIndexRoute = WorkforceEmployeesIndexRouteImport.update({
  id: '/workforce/employees/',
  path: '/workforce/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceEmployeesEmployeeIdRoute =
  WorkforceEmployeesEmployeeIdRouteImport.update({
    id: '/workforce/employees/$employeeId',
    path: '/workforce/employees/$employeeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryPlansPlanIdEditRoute = DeliveryPlansPlanIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DeliveryPlansPlanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/engagements': typeof EngagementsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/requirements': typeof RequirementsRoute
  '/scope': typeof ScopeRoute
  '/uat': typeof UatRoute
  '/administration/approval-policies': typeof AdministrationApprovalPoliciesRoute
  '/administration/contact-groups': typeof AdministrationContactGroupsRoute
  '/administration/engagements': typeof AdministrationEngagementsRoute
  '/administration/months': typeof AdministrationMonthsRoute
  '/attendance/leave': typeof AttendanceLeaveRoute
  '/attendance/month-close': typeof AttendanceMonthCloseRoute
  '/attendance/regularizations': typeof AttendanceRegularizationsRoute
  '/attendance/today': typeof AttendanceTodayRoute
  '/certification/$monthId': typeof CertificationMonthIdRouteWithChildren
  '/confirmation/$monthId': typeof ConfirmationMonthIdRoute
  '/delivery/integration-health': typeof DeliveryIntegrationHealthRoute
  '/finance/procurement': typeof FinanceProcurementRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/workforce/administration': typeof WorkforceAdministrationRoute
  '/certification/': typeof CertificationIndexRoute
  '/confirmation/': typeof ConfirmationIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/migration/': typeof MigrationIndexRoute
  '/administration/approval-requests/$requestId': typeof AdministrationApprovalRequestsRequestIdRoute
  '/certification/$monthId/review': typeof CertificationMonthIdReviewRoute
  '/confirmation/requests/$requestId': typeof ConfirmationRequestsRequestIdRoute
  '/delivery/plans/$planId': typeof DeliveryPlansPlanIdRouteWithChildren
  '/delivery/plans/new': typeof DeliveryPlansNewRoute
  '/workforce/employees/$employeeId': typeof WorkforceEmployeesEmployeeIdRoute
  '/administration/approval-requests/': typeof AdministrationApprovalRequestsIndexRoute
  '/certification/$monthId/': typeof CertificationMonthIdIndexRoute
  '/delivery/plans/': typeof DeliveryPlansIndexRoute
  '/workforce/employees/': typeof WorkforceEmployeesIndexRoute
  '/delivery/plans/$planId/edit': typeof DeliveryPlansPlanIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/engagements': typeof EngagementsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/requirements': typeof RequirementsRoute
  '/scope': typeof ScopeRoute
  '/uat': typeof UatRoute
  '/administration/approval-policies': typeof AdministrationApprovalPoliciesRoute
  '/administration/contact-groups': typeof AdministrationContactGroupsRoute
  '/administration/engagements': typeof AdministrationEngagementsRoute
  '/administration/months': typeof AdministrationMonthsRoute
  '/attendance/leave': typeof AttendanceLeaveRoute
  '/attendance/month-close': typeof AttendanceMonthCloseRoute
  '/attendance/regularizations': typeof AttendanceRegularizationsRoute
  '/attendance/today': typeof AttendanceTodayRoute
  '/confirmation/$monthId': typeof ConfirmationMonthIdRoute
  '/delivery/integration-health': typeof DeliveryIntegrationHealthRoute
  '/finance/procurement': typeof FinanceProcurementRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/workforce/administration': typeof WorkforceAdministrationRoute
  '/certification': typeof CertificationIndexRoute
  '/confirmation': typeof ConfirmationIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/migration': typeof MigrationIndexRoute
  '/administration/approval-requests/$requestId': typeof AdministrationApprovalRequestsRequestIdRoute
  '/certification/$monthId/review': typeof CertificationMonthIdReviewRoute
  '/confirmation/requests/$requestId': typeof ConfirmationRequestsRequestIdRoute
  '/delivery/plans/$planId': typeof DeliveryPlansPlanIdRouteWithChildren
  '/delivery/plans/new': typeof DeliveryPlansNewRoute
  '/workforce/employees/$employeeId': typeof WorkforceEmployeesEmployeeIdRoute
  '/administration/approval-requests': typeof AdministrationApprovalRequestsIndexRoute
  '/certification/$monthId': typeof CertificationMonthIdIndexRoute
  '/delivery/plans': typeof DeliveryPlansIndexRoute
  '/workforce/employees': typeof WorkforceEmployeesIndexRoute
  '/delivery/plans/$planId/edit': typeof DeliveryPlansPlanIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/engagements': typeof EngagementsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/requirements': typeof RequirementsRoute
  '/scope': typeof ScopeRoute
  '/uat': typeof UatRoute
  '/administration/approval-policies': typeof AdministrationApprovalPoliciesRoute
  '/administration/contact-groups': typeof AdministrationContactGroupsRoute
  '/administration/engagements': typeof AdministrationEngagementsRoute
  '/administration/months': typeof AdministrationMonthsRoute
  '/attendance/leave': typeof AttendanceLeaveRoute
  '/attendance/month-close': typeof AttendanceMonthCloseRoute
  '/attendance/regularizations': typeof AttendanceRegularizationsRoute
  '/attendance/today': typeof AttendanceTodayRoute
  '/certification/$monthId': typeof CertificationMonthIdRouteWithChildren
  '/confirmation/$monthId': typeof ConfirmationMonthIdRoute
  '/delivery/integration-health': typeof DeliveryIntegrationHealthRoute
  '/finance/procurement': typeof FinanceProcurementRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/workforce/administration': typeof WorkforceAdministrationRoute
  '/certification/': typeof CertificationIndexRoute
  '/confirmation/': typeof ConfirmationIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/migration/': typeof MigrationIndexRoute
  '/administration/approval-requests/$requestId': typeof AdministrationApprovalRequestsRequestIdRoute
  '/certification/$monthId/review': typeof CertificationMonthIdReviewRoute
  '/confirmation/requests/$requestId': typeof ConfirmationRequestsRequestIdRoute
  '/delivery/plans/$planId': typeof DeliveryPlansPlanIdRouteWithChildren
  '/delivery/plans/new': typeof DeliveryPlansNewRoute
  '/workforce/employees/$employeeId': typeof WorkforceEmployeesEmployeeIdRoute
  '/administration/approval-requests/': typeof AdministrationApprovalRequestsIndexRoute
  '/certification/$monthId/': typeof CertificationMonthIdIndexRoute
  '/delivery/plans/': typeof DeliveryPlansIndexRoute
  '/workforce/employees/': typeof WorkforceEmployeesIndexRoute
  '/delivery/plans/$planId/edit': typeof DeliveryPlansPlanIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/engagements'
    | '/invoices'
    | '/login'
    | '/requirements'
    | '/scope'
    | '/uat'
    | '/administration/approval-policies'
    | '/administration/contact-groups'
    | '/administration/engagements'
    | '/administration/months'
    | '/attendance/leave'
    | '/attendance/month-close'
    | '/attendance/regularizations'
    | '/attendance/today'
    | '/certification/$monthId'
    | '/confirmation/$monthId'
    | '/delivery/integration-health'
    | '/finance/procurement'
    | '/finance/reports'
    | '/workforce/administration'
    | '/certification/'
    | '/confirmation/'
    | '/finance/'
    | '/migration/'
    | '/administration/approval-requests/$requestId'
    | '/certification/$monthId/review'
    | '/confirmation/requests/$requestId'
    | '/delivery/plans/$planId'
    | '/delivery/plans/new'
    | '/workforce/employees/$employeeId'
    | '/administration/approval-requests/'
    | '/certification/$monthId/'
    | '/delivery/plans/'
    | '/workforce/employees/'
    | '/delivery/plans/$planId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/engagements'
    | '/invoices'
    | '/login'
    | '/requirements'
    | '/scope'
    | '/uat'
    | '/administration/approval-policies'
    | '/administration/contact-groups'
    | '/administration/engagements'
    | '/administration/months'
    | '/attendance/leave'
    | '/attendance/month-close'
    | '/attendance/regularizations'
    | '/attendance/today'
    | '/confirmation/$monthId'
    | '/delivery/integration-health'
    | '/finance/procurement'
    | '/finance/reports'
    | '/workforce/administration'
    | '/certification'
    | '/confirmation'
    | '/finance'
    | '/migration'
    | '/administration/approval-requests/$requestId'
    | '/certification/$monthId/review'
    | '/confirmation/requests/$requestId'
    | '/delivery/plans/$planId'
    | '/delivery/plans/new'
    | '/workforce/employees/$employeeId'
    | '/administration/approval-requests'
    | '/certification/$monthId'
    | '/delivery/plans'
    | '/workforce/employees'
    | '/delivery/plans/$planId/edit'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/engagements'
    | '/invoices'
    | '/login'
    | '/requirements'
    | '/scope'
    | '/uat'
    | '/administration/approval-policies'
    | '/administration/contact-groups'
    | '/administration/engagements'
    | '/administration/months'
    | '/attendance/leave'
    | '/attendance/month-close'
    | '/attendance/regularizations'
    | '/attendance/today'
    | '/certification/$monthId'
    | '/confirmation/$monthId'
    | '/delivery/integration-health'
    | '/finance/procurement'
    | '/finance/reports'
    | '/workforce/administration'
    | '/certification/'
    | '/confirmation/'
    | '/finance/'
    | '/migration/'
    | '/administration/approval-requests/$requestId'
    | '/certification/$monthId/review'
    | '/confirmation/requests/$requestId'
    | '/delivery/plans/$planId'
    | '/delivery/plans/new'
    | '/workforce/employees/$employeeId'
    | '/administration/approval-requests/'
    | '/certification/$monthId/'
    | '/delivery/plans/'
    | '/workforce/employees/'
    | '/delivery/plans/$planId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  EngagementsRoute: typeof EngagementsRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  RequirementsRoute: typeof RequirementsRoute
  ScopeRoute: typeof ScopeRoute
  UatRoute: typeof UatRoute
  AdministrationApprovalPoliciesRoute: typeof AdministrationApprovalPoliciesRoute
  AdministrationContactGroupsRoute: typeof AdministrationContactGroupsRoute
  AdministrationEngagementsRoute: typeof AdministrationEngagementsRoute
  AdministrationMonthsRoute: typeof AdministrationMonthsRoute
  AttendanceLeaveRoute: typeof AttendanceLeaveRoute
  AttendanceMonthCloseRoute: typeof AttendanceMonthCloseRoute
  AttendanceRegularizationsRoute: typeof AttendanceRegularizationsRoute
  AttendanceTodayRoute: typeof AttendanceTodayRoute
  CertificationMonthIdRoute: typeof CertificationMonthIdRouteWithChildren
  ConfirmationMonthIdRoute: typeof ConfirmationMonthIdRoute
  DeliveryIntegrationHealthRoute: typeof DeliveryIntegrationHealthRoute
  FinanceProcurementRoute: typeof FinanceProcurementRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  WorkforceAdministrationRoute: typeof WorkforceAdministrationRoute
  CertificationIndexRoute: typeof CertificationIndexRoute
  ConfirmationIndexRoute: typeof ConfirmationIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  MigrationIndexRoute: typeof MigrationIndexRoute
  AdministrationApprovalRequestsRequestIdRoute: typeof AdministrationApprovalRequestsRequestIdRoute
  ConfirmationRequestsRequestIdRoute: typeof ConfirmationRequestsRequestIdRoute
  DeliveryPlansPlanIdRoute: typeof DeliveryPlansPlanIdRouteWithChildren
  DeliveryPlansNewRoute: typeof DeliveryPlansNewRoute
  WorkforceEmployeesEmployeeIdRoute: typeof WorkforceEmployeesEmployeeIdRoute
  AdministrationApprovalRequestsIndexRoute: typeof AdministrationApprovalRequestsIndexRoute
  DeliveryPlansIndexRoute: typeof DeliveryPlansIndexRoute
  WorkforceEmployeesIndexRoute: typeof WorkforceEmployeesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uat': {
      id: '/uat'
      path: '/uat'
      fullPath: '/uat'
      preLoaderRoute: typeof UatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/approval-policies': {
      id: '/administration/approval-policies'
      path: '/administration/approval-policies'
      fullPath: '/administration/approval-policies'
      preLoaderRoute: typeof AdministrationApprovalPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/contact-groups': {
      id: '/administration/contact-groups'
      path: '/administration/contact-groups'
      fullPath: '/administration/contact-groups'
      preLoaderRoute: typeof AdministrationContactGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/engagements': {
      id: '/administration/engagements'
      path: '/administration/engagements'
      fullPath: '/administration/engagements'
      preLoaderRoute: typeof AdministrationEngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/months': {
      id: '/administration/months'
      path: '/administration/months'
      fullPath: '/administration/months'
      preLoaderRoute: typeof AdministrationMonthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/leave': {
      id: '/attendance/leave'
      path: '/attendance/leave'
      fullPath: '/attendance/leave'
      preLoaderRoute: typeof AttendanceLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/month-close': {
      id: '/attendance/month-close'
      path: '/attendance/month-close'
      fullPath: '/attendance/month-close'
      preLoaderRoute: typeof AttendanceMonthCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/regularizations': {
      id: '/attendance/regularizations'
      path: '/attendance/regularizations'
      fullPath: '/attendance/regularizations'
      preLoaderRoute: typeof AttendanceRegularizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/today': {
      id: '/attendance/today'
      path: '/attendance/today'
      fullPath: '/attendance/today'
      preLoaderRoute: typeof AttendanceTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification/': {
      id: '/certification/'
      path: '/certification'
      fullPath: '/certification/'
      preLoaderRoute: typeof CertificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification/$monthId': {
      id: '/certification/$monthId'
      path: '/certification/$monthId'
      fullPath: '/certification/$monthId'
      preLoaderRoute: typeof CertificationMonthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/': {
      id: '/confirmation/'
      path: '/confirmation'
      fullPath: '/confirmation/'
      preLoaderRoute: typeof ConfirmationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$monthId': {
      id: '/confirmation/$monthId'
      path: '/confirmation/$monthId'
      fullPath: '/confirmation/$monthId'
      preLoaderRoute: typeof ConfirmationMonthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/integration-health': {
      id: '/delivery/integration-health'
      path: '/delivery/integration-health'
      fullPath: '/delivery/integration-health'
      preLoaderRoute: typeof DeliveryIntegrationHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/procurement': {
      id: '/finance/procurement'
      path: '/finance/procurement'
      fullPath: '/finance/procurement'
      preLoaderRoute: typeof FinanceProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration/': {
      id: '/migration/'
      path: '/migration'
      fullPath: '/migration/'
      preLoaderRoute: typeof MigrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/administration': {
      id: '/workforce/administration'
      path: '/workforce/administration'
      fullPath: '/workforce/administration'
      preLoaderRoute: typeof WorkforceAdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/approval-requests/': {
      id: '/administration/approval-requests/'
      path: '/administration/approval-requests'
      fullPath: '/administration/approval-requests/'
      preLoaderRoute: typeof AdministrationApprovalRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/approval-requests/$requestId': {
      id: '/administration/approval-requests/$requestId'
      path: '/administration/approval-requests/$requestId'
      fullPath: '/administration/approval-requests/$requestId'
      preLoaderRoute: typeof AdministrationApprovalRequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification/$monthId/': {
      id: '/certification/$monthId/'
      path: '/'
      fullPath: '/certification/$monthId/'
      preLoaderRoute: typeof CertificationMonthIdIndexRouteImport
      parentRoute: typeof CertificationMonthIdRoute
    }
    '/certification/$monthId/review': {
      id: '/certification/$monthId/review'
      path: '/review'
      fullPath: '/certification/$monthId/review'
      preLoaderRoute: typeof CertificationMonthIdReviewRouteImport
      parentRoute: typeof CertificationMonthIdRoute
    }
    '/confirmation/requests/$requestId': {
      id: '/confirmation/requests/$requestId'
      path: '/confirmation/requests/$requestId'
      fullPath: '/confirmation/requests/$requestId'
      preLoaderRoute: typeof ConfirmationRequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/plans/': {
      id: '/delivery/plans/'
      path: '/delivery/plans'
      fullPath: '/delivery/plans/'
      preLoaderRoute: typeof DeliveryPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/plans/$planId': {
      id: '/delivery/plans/$planId'
      path: '/delivery/plans/$planId'
      fullPath: '/delivery/plans/$planId'
      preLoaderRoute: typeof DeliveryPlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/plans/new': {
      id: '/delivery/plans/new'
      path: '/delivery/plans/new'
      fullPath: '/delivery/plans/new'
      preLoaderRoute: typeof DeliveryPlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/employees/': {
      id: '/workforce/employees/'
      path: '/workforce/employees'
      fullPath: '/workforce/employees/'
      preLoaderRoute: typeof WorkforceEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/employees/$employeeId': {
      id: '/workforce/employees/$employeeId'
      path: '/workforce/employees/$employeeId'
      fullPath: '/workforce/employees/$employeeId'
      preLoaderRoute: typeof WorkforceEmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/plans/$planId/edit': {
      id: '/delivery/plans/$planId/edit'
      path: '/edit'
      fullPath: '/delivery/plans/$planId/edit'
      preLoaderRoute: typeof DeliveryPlansPlanIdEditRouteImport
      parentRoute: typeof DeliveryPlansPlanIdRoute
    }
  }
}

interface CertificationMonthIdRouteChildren {
  CertificationMonthIdReviewRoute: typeof CertificationMonthIdReviewRoute
  CertificationMonthIdIndexRoute: typeof CertificationMonthIdIndexRoute
}

const CertificationMonthIdRouteChildren: CertificationMonthIdRouteChildren = {
  CertificationMonthIdReviewRoute: CertificationMonthIdReviewRoute,
  CertificationMonthIdIndexRoute: CertificationMonthIdIndexRoute,
}

const CertificationMonthIdRouteWithChildren =
  CertificationMonthIdRoute._addFileChildren(CertificationMonthIdRouteChildren)

interface DeliveryPlansPlanIdRouteChildren {
  DeliveryPlansPlanIdEditRoute: typeof DeliveryPlansPlanIdEditRoute
}

const DeliveryPlansPlanIdRouteChildren: DeliveryPlansPlanIdRouteChildren = {
  DeliveryPlansPlanIdEditRoute: DeliveryPlansPlanIdEditRoute,
}

const DeliveryPlansPlanIdRouteWithChildren =
  DeliveryPlansPlanIdRoute._addFileChildren(DeliveryPlansPlanIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  EngagementsRoute: EngagementsRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  RequirementsRoute: RequirementsRoute,
  ScopeRoute: ScopeRoute,
  UatRoute: UatRoute,
  AdministrationApprovalPoliciesRoute: AdministrationApprovalPoliciesRoute,
  AdministrationContactGroupsRoute: AdministrationContactGroupsRoute,
  AdministrationEngagementsRoute: AdministrationEngagementsRoute,
  AdministrationMonthsRoute: AdministrationMonthsRoute,
  AttendanceLeaveRoute: AttendanceLeaveRoute,
  AttendanceMonthCloseRoute: AttendanceMonthCloseRoute,
  AttendanceRegularizationsRoute: AttendanceRegularizationsRoute,
  AttendanceTodayRoute: AttendanceTodayRoute,
  CertificationMonthIdRoute: CertificationMonthIdRouteWithChildren,
  ConfirmationMonthIdRoute: ConfirmationMonthIdRoute,
  DeliveryIntegrationHealthRoute: DeliveryIntegrationHealthRoute,
  FinanceProcurementRoute: FinanceProcurementRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  WorkforceAdministrationRoute: WorkforceAdministrationRoute,
  CertificationIndexRoute: CertificationIndexRoute,
  ConfirmationIndexRoute: ConfirmationIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  MigrationIndexRoute: MigrationIndexRoute,
  AdministrationApprovalRequestsRequestIdRoute:
    AdministrationApprovalRequestsRequestIdRoute,
  ConfirmationRequestsRequestIdRoute: ConfirmationRequestsRequestIdRoute,
  DeliveryPlansPlanIdRoute: DeliveryPlansPlanIdRouteWithChildren,
  DeliveryPlansNewRoute: DeliveryPlansNewRoute,
  WorkforceEmployeesEmployeeIdRoute: WorkforceEmployeesEmployeeIdRoute,
  AdministrationApprovalRequestsIndexRoute:
    AdministrationApprovalRequestsIndexRoute,
  DeliveryPlansIndexRoute: DeliveryPlansIndexRoute,
  WorkforceEmployeesIndexRoute: WorkforceEmployeesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
