/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UatRouteImport } from './routes/uat'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'

const UatRoute = UatRouteImport.update({
  id: '/uat',
  path: '/uat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/engagements': typeof EngagementsRoute
  '/requirements': typeof RequirementsRoute
  '/scope': typeof ScopeRoute
  '/uat': typeof UatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/engagements': typeof EngagementsRoute
  '/requirements': typeof RequirementsRoute
  '/scope': typeof ScopeRoute
  '/uat': typeof UatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/engagements': typeof EngagementsRoute
  '/requirements': typeof RequirementsRoute
  '/scope': typeof ScopeRoute
  '/uat': typeof UatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/engagements'
    | '/requirements'
    | '/scope'
    | '/uat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/approvals' | '/engagements' | '/requirements' | '/scope' | '/uat'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/engagements'
    | '/requirements'
    | '/scope'
    | '/uat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  EngagementsRoute: typeof EngagementsRoute
  RequirementsRoute: typeof RequirementsRoute
  ScopeRoute: typeof ScopeRoute
  UatRoute: typeof UatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uat': {
      id: '/uat'
      path: '/uat'
      fullPath: '/uat'
      preLoaderRoute: typeof UatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  EngagementsRoute: EngagementsRoute,
  RequirementsRoute: RequirementsRoute,
  ScopeRoute: ScopeRoute,
  UatRoute: UatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
